import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

export default {
  getting_started: [{ type: "autogenerated", dirName: "Rapid/1-Getting Started" }],
  user_manual: [{ type: "autogenerated", dirName: "Rapid/2-User Manual" }],
  keyper_manual: [{ type: "autogenerated", dirName: "Rapid/3-Keyper Manual" }],
  developer_manual: [{ type: "autogenerated", dirName: "Rapid/4-Developer Manual" }]
} as SidebarsConfig;
