import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

export default {
  getting_started: [{ type: "autogenerated", dirName: "Rapid/1-Getting Started" }],
  rapid_standard: [{ type: "autogenerated", dirName: "Rapid/2-Rapid Standard" }],
  user_manual: [{ type: "autogenerated", dirName: "Rapid/3-User Manual" }],
  keyper_manual: [{ type: "autogenerated", dirName: "Rapid/4-Keyper Manual" }]
} as SidebarsConfig;
