import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

export default {
  using_designer: [
    { type: 'autogenerated', dirName: './training/Rapid Standard CRM' }
  ],
  using_explorer: [
    { type: 'autogenerated', dirName: './training/Using Explorer' }
  ],
  using_rpform: [
    { type: 'autogenerated', dirName: './training/Using RpForm' }
  ],
  using_workflow: [
    { type: 'autogenerated', dirName: './training/Using Workflow' }
  ]
} as SidebarsConfig;
