import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

export default {
  using_explorer: [
    { type: 'autogenerated', dirName: './training/System Build Foundational' }
  ],
  using_rpform: [
    { type: 'autogenerated', dirName: './training/Using RpForm' }
  ],
  using_workflow: [
    { type: 'autogenerated', dirName: './training/Using Workflow' }
  ]
} as SidebarsConfig;
