name: Issue Report
description: File a documentation issue report
title: "[A short description of your issue]: "
labels: ["Report"]
assignees:
  - MattFranklin-Rapid
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-is-the-issue
    attributes:
      label: What is the issue?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A clear description of the issue"
    validations:
      required: true
  - type: dropdown
    validations:
      required: true
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
